### ISSUE TITLE
Text_18.md

### ISSUE THREAD

**Issue by DasNordlicht** [ffslfl/gewerbe-Flyer#14]
Beispiel für Routername ohne "FF-" beginnen

    "Für wen" mit Fragezeichen

    "f+r wen"- LIste alles Mehrzahl

**Comment by DasNordlicht** [comment]
Beispiel für Routername ohne "FF-" beginnen Ist in Text_17.md

**Comment by DasNordlicht** [comment]
Fehler bereinigt

**Comment by rubo77** [comment]
sehr schön, nur noch: "Kleingärtnervereinen" muss "Kleingärtnervereine" heissen
